#pragma once

#define BLINK_TIMER_INTERVAL 5.0f
#define BLINK_START_TIME 2.2f
#define BLINK_END_TIME 3.0f

#define BLINK_LONGER_WHEN_HURT true

#define BLINK_HOLD_MIN_THRESHOLD 0.1666f
#define BLINK_HOLD_MAX_THRESHOLD 3.5f

#define ENEMY_FAST_ON_BLINK true
#define ENEMY_STATUE_SPEED 2.5f
#define ENEMY_STATUE_SPEED_BLINK 4.0f